/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackButton: typeof import('./src/components/BackButton.vue')['default']
    CreateTask: typeof import('./src/components/CreateTask.vue')['default']
    CreateUser: typeof import('./src/components/CreateUser.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpdateTask: typeof import('./src/components/UpdateTask.vue')['default']
    UpdateUser: typeof import('./src/components/UpdateUser.vue')['default']
  }
}
