/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CRUD: typeof import('./src/components/CRUD.vue')['default']
    Table: typeof import('./src/components/Table.vue')['default']
    Tasks: typeof import('./src/components/Tasks.vue')['default']
    Temp: typeof import('./src/components/temp.vue')['default']
    Users: typeof import('./src/components/Users.vue')['default']
  }
}
